"""
Ruby's Tools for ComfyUI

Personal utility, type converter, RP, and tool nodes.
"""

from .nodes.denoise_seed_iterator import NODE_CLASS_MAPPINGS as DENOISE_SEED_MAPPINGS
from .nodes.denoise_seed_iterator import NODE_DISPLAY_NAME_MAPPINGS as DENOISE_SEED_DISPLAY_MAPPINGS
from .nodes.type_converters import NODE_CLASS_MAPPINGS as TYPE_CONVERTER_MAPPINGS
from .nodes.type_converters import NODE_DISPLAY_NAME_MAPPINGS as TYPE_CONVERTER_DISPLAY_MAPPINGS
from .nodes.text_tools import NODE_CLASS_MAPPINGS as TEXT_TOOLS_MAPPINGS
from .nodes.text_tools import NODE_DISPLAY_NAME_MAPPINGS as TEXT_TOOLS_DISPLAY_MAPPINGS
from .nodes.presets import NODE_CLASS_MAPPINGS as PRESET_MAPPINGS
from .nodes.presets import NODE_DISPLAY_NAME_MAPPINGS as PRESET_DISPLAY_MAPPINGS
from .nodes.memory import NODE_CLASS_MAPPINGS as MEMORY_MAPPINGS
from .nodes.memory import NODE_DISPLAY_NAME_MAPPINGS as MEMORY_DISPLAY_MAPPINGS
from .nodes.character import NODE_CLASS_MAPPINGS as CHARACTER_MAPPINGS
from .nodes.character import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_DISPLAY_MAPPINGS
from .nodes.context import NODE_CLASS_MAPPINGS as CONTEXT_MAPPINGS
from .nodes.context import NODE_DISPLAY_NAME_MAPPINGS as CONTEXT_DISPLAY_MAPPINGS
from .nodes.filename_aide import NODE_CLASS_MAPPINGS as FILENAME_AIDE_MAPPINGS
from .nodes.filename_aide import NODE_DISPLAY_NAME_MAPPINGS as FILENAME_AIDE_DISPLAY_MAPPINGS
from .nodes.crypto import NODE_CLASS_MAPPINGS as CRYPTO_MAPPINGS
from .nodes.crypto import NODE_DISPLAY_NAME_MAPPINGS as CRYPTO_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **DENOISE_SEED_MAPPINGS,
    **TYPE_CONVERTER_MAPPINGS,
    **TEXT_TOOLS_MAPPINGS,
    **PRESET_MAPPINGS,
    **MEMORY_MAPPINGS,
    **CHARACTER_MAPPINGS,
    **CONTEXT_MAPPINGS,
    **FILENAME_AIDE_MAPPINGS,
    **CRYPTO_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **DENOISE_SEED_DISPLAY_MAPPINGS,
    **TYPE_CONVERTER_DISPLAY_MAPPINGS,
    **TEXT_TOOLS_DISPLAY_MAPPINGS,
    **PRESET_DISPLAY_MAPPINGS,
    **MEMORY_DISPLAY_MAPPINGS,
    **CHARACTER_DISPLAY_MAPPINGS,
    **CONTEXT_DISPLAY_MAPPINGS,
    **FILENAME_AIDE_DISPLAY_MAPPINGS,
    **CRYPTO_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
